### ISSUE TITLE
phpBB 3.1

### ISSUE THREAD

**Issue by rjdevries** [cyberalien/phpbb3_mobile#2]
Hello,

will there be a version for phpBB 3.1 of this great theme?
Or is there another way to get this theme to work on 3.1?

It will be greatly appreciated!

Greetings, Ronald

**Comment by cyberalien** [comment]
No. phpBB 3.1 styles are fully responsive, there is no need for mobile style.

**Comment by rjdevries** [comment]
Please read this discussion. https://www.phpbb.com/community/viewtopic.php?f=64&t=2275226
I don't think you can call it "fully" responsive.
But if you think otherwise, no problem. I'll have to search on.

**Comment by cyberalien** [comment]
Its responsive enough. There are minor issues, but nothing that would make it unusable on mobile devices. 

Almost all of those minor issues are caused by attempt to make conversion from 3.0 to 3.1 as smooth as possible, which seemed like a good idea at the time, but now I think it was a bad idea. They can all be fixed with few changes in css code.

However it is much better than mobile style. Mobile style uses one size for all approach, causing layout to look the same on small phones and large phones. Responsive prosilver fits more content on wider devices.
